import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { RootLayoutClient } from "./layout.client";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Bimbel | Worldpedia Education",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/general/logo.png",
      type: "image/png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontClassName = cn(plusJakartaSans.variable);

  return (
    <RootLayoutClient fontClassName={fontClassName}>
      {children}
    </RootLayoutClient>
  );
}